project_id = "bmofuisxcssgfuicvrou"

[functions.analyze-patient-vitals]
verify_jwt = false

[functions.ai-telemedicine-diagnosis]
verify_jwt = false

[functions.scan-medication-barcode]
verify_jwt = false

[functions.analyze-dental-imaging]
verify_jwt = false

[functions.openevidence-search]
verify_jwt = true

[functions.secure-data-handler]
verify_jwt = false

[functions.ai-clinical-diagnosis]
verify_jwt = false

[functions.generate-medical-document]
verify_jwt = true

[functions.get-elevenlabs-key]
verify_jwt = true
