// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmofuisxcssgfuicvrou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtb2Z1aXN4Y3NzZ2Z1aWN2cm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjQwMjksImV4cCI6MjA2NjQ0MDAyOX0.A9HmtSLR8geu137fq496SNTDH9bKlcnegYU-fkKDZCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);